---
- name: Create build directory
  file:
    path: "{{ build_dir }}"
    state: directory

- name: Render templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "Dockerfile.j2",    dest: "{{ build_dir }}/coriolis-web-proxy.Dockerfile" }
    - { src: "webproxy_start.j2", dest: "{{ build_dir }}/webproxy_start" }
  notify:
    - "build coriolis-web-proxy"

- name: "Get Docker image stat"
  docker_image_info:
    name: "{{ docker_registry }}/{{ docker_namespace }}/coriolis-web-proxy:{{ docker_images_tag }}"
  register: docker_image_info

- name: "Trigger Docker image build"
  command: /bin/true
  notify:
    - "build coriolis-web-proxy"
  when: docker_image_info.images | length == 0
