---
- name: Remove Docker container
  docker_container:
    state: absent
    name: coriolis-web-proxy

- name: Remove Docker image
  docker_image:
    state: absent
    force_absent: yes
    name: "{{ coriolis_web_proxy_docker_image_url }}"

- name: Remove certs directory
  file:
    state: absent
    path: "{{ coriolis_certs_dir }}"
