---
- name: Setup coriolis-web-proxy container
  docker_container:
    name: coriolis-web-proxy
    image: "{{ coriolis_web_proxy_docker_image_url }}"
    pull: "{{ docker_pull_images }}"
    hostname: coriolis-web-proxy
    state: started
    restart_policy: unless-stopped
    network_mode: host
    volumes:
      - "{{ coriolis_config_dir }}:{{ coriolis_config_dir }}"
      - "{{ coriolis_certs_dir }}:{{ coriolis_certs_dir }}:ro"
