FROM golang:alpine AS builder
LABEL stage=builder

ENV GO111MODULE=on
ADD coriolis-compressor/ /tmp/coriolis-compressor
WORKDIR /tmp/coriolis-compressor/cmd/coriolis-compressor/

RUN GOOS=linux GOARCH=amd64 go build -mod vendor \
    -o /coriolis-compressor \
    -tags osusergo,netgo,sqlite_omit_load_extension \
    -ldflags "-extldflags '-static' -s -w" .

FROM busybox
COPY --from=builder /coriolis-compressor /coriolis-compressor
RUN chmod +x /coriolis-compressor

ENTRYPOINT ["/bin/sh", "-c", "/coriolis-compressor -bind $COMPRESSOR_ADDRESS"]
