---
- name: Setup coriolis-web container
  docker_container:
    name: coriolis-web
    image: "{{ coriolis_web_docker_image_url }}"
    pull: "{{ docker_pull_images }}"
    hostname: coriolis-web
    state: started
    restart_policy: unless-stopped
    network_mode: host
    env:
      CA_FINGERPRINT: "{{ coriolis_web_step_dir }}/fingerprint"
      CORIOLIS_LICENSING_BASE_URL: "/licensing"
      MOD_JSON: "{{ coriolis_web_mod_dir }}/ui-mod.json"
    volumes:
      - "{{ coriolis_web_mod_dir }}:{{ coriolis_web_mod_dir }}:rw"
      - "{{ step_ca_home }}:{{ coriolis_web_step_dir }}"
      - "{{ coriolis_logger_socket_dir }}:{{ coriolis_logger_socket_dir }}"
