---
- hosts: localhost
  tasks:
    - name: Creating build directory
      file:
        path: ./build
        state: directory

    - name: Creating Dockerfile
      template: src=Dockerfile.server.j2 dest=./build/Dockerfile.server

    - name: Cloning coriolis git repositories
      git: repo={{ item.url }} dest=./build/{{item.name}} update=yes force=yes version={{item.version}}
      with_items:
        - { url: "git@bitbucket.org:cloudbase/coriolis-licensing-server.git", name: coriolis-licensing-server, version: master}

    - name: Building coriolis docker images
      docker_image: path=./build dockerfile={{item.dockerfile}} name={{ docker_registry }}/{{ coriolis_containers_namespace }}/{{item.name}} pull=False push={{ docker_push_images}} tag={{ docker_images_tag }}
      with_items:
        - { dockerfile: Dockerfile.server, name: coriolis-licensing-server }
