---
- hosts: localhost
  tasks:
    - name: Creating build directory
      file:
        path: ./build
        state: directory

    - name: Creating Dockerfile
      template: src=Dockerfile.server.j2 dest=./build/Dockerfile.server

    - name: Cloning coriolis git repositories
      vars:
        custom_repo_owner: "{{ custom_repo_owner_names['licensing']|default ('cloudbase') }}"
        custom_repo_branch: "{{ custom_repo_branch_names['licensing']|default ('master') }}"
      git:
        repo: "git@bitbucket.org:{{ custom_repo_owner }}/coriolis-licensing-server.git"
        dest: "./build/coriolis-licensing-server"
        update: yes
        force: yes
        version: "{{ custom_repo_branch }}"

    - name: Building coriolis docker images
      docker_image: path=./build dockerfile={{item.dockerfile}} name={{ docker_registry }}/{{ coriolis_containers_namespace }}/{{item.name}} pull=False push={{ docker_push_images}} tag={{ docker_images_tag }}
      with_items:
        - { dockerfile: Dockerfile.server, name: coriolis-licensing-server }
