---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ influxdb_config_dir }}"
    - "{{ coriolis_logger_config_dir }}"

- name: Create influxdb data volume
  docker_volume:
    name: "{{ influxdb_data_volume_name }}"

- include_tasks: setup.yml
