---
- name: Remove Docker containers
  docker_container:
    state: absent
    name: "{{ item }}"
  with_items:
    - coriolis-api
    - coriolis-conductor
    - coriolis-transfer-cron
    - coriolis-worker
    - coriolis-web
    - coriolis-scheduler
    - coriolis-minion-manager
    - coriolis-deployer-manager
    - coriolis-logger
    - influxdb

- name: Remove Docker image
  docker_image:
    state: absent
    force_absent: yes
    name: "{{ coriolis_logger_docker_image_url }}"

- name: Remove volumes
  docker_volume:
    state: absent
    name: "{{ item }}"
  with_items:
    - "{{ influxdb_data_volume_name }}"
