---
- name: Remove Docker containers
  docker_container:
    state: absent
    name: "{{ item }}"
  with_items:
    - coriolis-api
    - coriolis-conductor
    - coriolis-replica-cron
    - coriolis-worker
    - coriolis-web
    - coriolis-logger
    - influxdb

- name: Remove Docker image
  docker_image:
    state: absent
    force_absent: yes
    name: "{{ docker_images_namespace }}/coriolis-logger:{{ docker_images_tag }}"

- name: Remove volumes
  docker_volume:
    state: absent
    name: "{{ item }}"
  with_items:
    - "{{ influxdb_data_volume_name }}"
    - "{{ coriolis_logger_volume_name }}"
