---
- name: Remove Docker container
  docker_container:
    state: absent
    name: "coriolis-logger"

- name: Remove Docker image
  docker_image:
    state: absent
    force_absent: yes
    name: "{{ docker_registry }}/{{ docker_namespace }}/coriolis-logger"

- name: "Trigger influxdb update"
  command: /bin/true
  notify:
    - "setup influxdb"

- name: "Trigger coriolis-logger update"
  command: /bin/true
  notify:
    - "setup coriolis-logger"
