---
- name: Remove Docker container
  docker_container:
    state: absent
    name: "coriolis-logger"

- name: Remove Docker image
  docker_image:
    state: absent
    force_absent: yes
    name: "{{ docker_registry }}/{{ docker_namespace }}/coriolis-logger:{{ docker_images_tag }}"

- include_tasks: setup_logger_container.yml
