---
- name: Remove Docker container
  docker_container:
    state: absent
    name: coriolis-api

- name: Remove Docker image
  docker_image:
    state: absent
    force_absent: yes
    name: "{{ docker_images_namespace }}/coriolis-api:{{ docker_images_tag }}"

- include_tasks: setup_api_container.yml
