---
- hosts: localhost
  vars:
      all_providers: "{{ export_providers | union(import_providers) }}"
  tasks:
    - name: Creating build directory
      file:
        path: ./build
        state: directory

    - name: Creating Docker build files
      template: src={{ docker_template }}/{{ item.name }}.j2 dest=./build/{{ item.name }}
      with_items:
        - { name: Dockerfile.base}
        - { name: Dockerfile.common}
        - { name: Dockerfile.api}
        - { name: Dockerfile.conductor}
        - { name: Dockerfile.replica_cron}
        - { name: Dockerfile.worker}
        - { name: Dockerfile.web}

    - name: Cloning coriolis-core
      vars:
        custom_repo_owner: "{{ custom_repo_owner_names['core']|default ('cloudbase') }}"
        custom_repo_branch: "{{ custom_repo_branch_names['core']|default ('master') }}"
      git:
        repo: "https://github.com/{{ custom_repo_owner }}/coriolis"
        dest: "./build/coriolis-core"
        update: yes
        force: yes
        version: "{{ custom_repo_branch }}"

    - name: Cloning coriolis-web
      vars:
        custom_repo_owner: "{{ custom_repo_owner_names['web']|default ('cloudbase') }}"
        custom_repo_branch: "{{ custom_repo_branch_names['web']|default ('master') }}"
      git:
        repo: "https://github.com/{{ custom_repo_owner }}/coriolis-web"
        dest: "./build/coriolis-web"
        update: yes
        force: yes
        version: "{{ custom_repo_branch }}"

    - name: Cloning provider repos
      vars:
        provider: "{{ item }}"
        custom_repo_owner: "{{ custom_repo_owner_names[provider]|default ('cloudbase') }}"
        custom_repo_branch: "{{ custom_repo_branch_names[provider]|default ('master') }}"
      git:
        repo: "git@bitbucket.org:{{ custom_repo_owner }}/coriolis-provider-{{ provider }}"
        dest: "./build/coriolis-provider-{{ provider }}"
        update: yes
        force: yes
        version: "{{ custom_repo_branch }}"
      with_items: "{{ all_providers }}"

    - name: Downloading libnfs RPM
      get_url:
        url: "{{ libnfs_rpm_url }}"
        dest: ./build/libnfs.x86_64.rpm
      register: result
      retries: 10
      delay: 5
      until: result is succeeded

    - name: Downloading libqemu
      get_url:
        url: "{{ libqemu_url }}"
        dest: ./build/libqemu.so.gz
      register: result
      retries: 10
      delay: 5
      until: result is succeeded

    - name: Building coriolis-base
      docker_image:
        path: ./build
        dockerfile: Dockerfile.base
        tag: "{{ docker_images_tag }}"
        push: "{{ docker_push_images}}"
        name: "{{ docker_registry }}/{{ coriolis_containers_namespace }}/coriolis-base"

    - name: Building coriolis docker images
      docker_image: path=./build dockerfile={{item.dockerfile}} name={{ docker_registry }}/{{ coriolis_containers_namespace }}/{{item.name}} pull=False push={{ docker_push_images}} tag={{ docker_images_tag }}
      with_items:
        - { dockerfile: Dockerfile.common, name: coriolis-common}
        - { dockerfile: Dockerfile.api, name: coriolis-api}
        - { dockerfile: Dockerfile.conductor, name: coriolis-conductor}
        - { dockerfile: Dockerfile.replica_cron, name: coriolis-replica-cron}
        - { dockerfile: Dockerfile.worker, name: coriolis-worker}
        - { dockerfile: Dockerfile.web, name: coriolis-web}
