coriolis_logger_socket_dir: /var/run/coriolis-logger
coriolis_logger_socket_name: logger.socket
coriolis_logger_socket_path: "{{ coriolis_logger_socket_dir }}/{{ coriolis_logger_socket_name }}"
coriolis_logger_config: '{{coriolis_logger_config_directory_container}}/coriolis-logger.toml'
coriolis_logger_config_directory_container: /etc/coriolis-logger