docker_registry: registry.cloudbase.it
docker_push_images: true
docker_images_tag: 1.0.0
docker_template: ol7
vmware_disklib_url: https://cloudbase.it/downloads/VMware-vix-disklib-6.5.0-5136645.x86_64.tar.gz
