---
- hosts: localhost
  vars:
    coriolis_debug: true
    coriolis_admin_endpoint: "http://{{ kolla_internal_vip_address }}:7667/v1/%(tenant_id)s"
    coriolis_internal_endpoint: "{{ coriolis_admin_endpoint }}"
    coriolis_public_endpoint: "{{ coriolis_admin_endpoint }}"
    keystone_host: "{{ kolla_internal_vip_address }}"
    keystone_auth_url: "{{ admin_protocol }}://{{ keystone_host }}:{{ keystone_admin_port }}"
    database_address: "{{ kolla_internal_vip_address }}"
    database_port: 3306
    database_user: "root"
    coriolis_database_name: "coriolis"
    coriolis_database_password: "change_this"
    rabbitmq_user: "openstack"
    rabbitmq_host: "{{ kolla_internal_vip_address }}"
    rabbitmq_port: 5672
    internal_protocol: "http"
    admin_protocol: "http"
    keystone_public_port: 5000
    keystone_admin_port: 35357
    coriolis_keystone_user: "coriolis"
    coriolis_keystone_password: "change_this_one_too"
    temp_keypair_password: "and_change_this_one"
    pv_drivers_url: "https://dl.dropboxusercontent.com/u/9060190/ovm_win_vp_drivers_3_2_3.zip"
    coriolis_export_base_path: /opt/coriolis/export
    coriolis_export_base_path_host: /opt/coriolis/export
  tasks:
    - name: Creating coriolis database
      mysql_db:
        login_host: "{{ database_address }}"
        login_port: "{{ database_port }}"
        login_user: "{{ database_user }}"
        login_password: "{{ database_password }}"
        name: "{{ coriolis_database_name }}"
      run_once: True

    - name: Creating coriolis database user and setting permissions
      mysql_user:
        login_host: "{{ database_address }}"
        login_port: "{{ database_port }}"
        login_user: "{{ database_user }}"
        login_password: "{{ database_password }}"
        name: "{{ coriolis_database_name }}"
        password: "{{ coriolis_database_password }}"
        host: "%"
        priv: "{{ coriolis_database_name }}.*:ALL"
        append_privs: "yes"
      run_once: True

    - name: Creating config directory
      file:
        path: /etc/coriolis
        state: directory

    - name: Creating log directory
      file:
        path: /var/log/coriolis
        state: directory

    - name: Creating Coriolis shared export path directory
      file:
        path: "{{ coriolis_export_base_path_host }}"
        state: directory

    - name: Creating coriolis.conf
      template:
        src: ./templates/coriolis.conf.j2
        dest: /etc/coriolis/coriolis.conf

    - name: Creating api-paste.ini
      template:
        src: ./templates/api-paste.ini.j2
        dest: /etc/coriolis/api-paste.ini

    - name: Checking Coriolis Keystone service
      shell: openstack service list  -c Name  | grep coriolis
      environment:
        OS_AUTH_URL: "{{ keystone_auth_url }}"
        OS_IDENTITY_API_VERSION: 3
        OS_PASSWORD: "{{ keystone_admin_password }}"
        OS_PROJECT_NAME: admin
        OS_TENANT_NAME: admin
        OS_USERNAME: admin
        OS_USER_DOMAIN_NAME: "default"
        OS_PROJECT_DOMAIN_NAME: "default"
      retries: 10
      delay: 5
      register: service_list

    - name: Creating Coriolis Keystone service
      command: openstack service create --name coriolis --description "Cloud Migration as a Service" migration
      environment:
        OS_AUTH_URL: "{{ keystone_auth_url }}"
        OS_IDENTITY_API_VERSION: 3
        OS_PASSWORD: "{{ keystone_admin_password }}"
        OS_PROJECT_NAME: admin
        OS_TENANT_NAME: admin
        OS_USERNAME: admin
        OS_USER_DOMAIN_NAME: "default"
        OS_PROJECT_DOMAIN_NAME: "default"
      run_once: True
      retries: 10
      delay: 5
      when: service_list.stdout_lines == 0

    - name: Checking Coriolis Keystone endpoints
      shell: openstack endpoint list  -c "Service Name" | grep coriolis
      environment:
        OS_AUTH_URL: "{{ keystone_auth_url }}"
        OS_IDENTITY_API_VERSION: 3
        OS_PASSWORD: "{{ keystone_admin_password }}"
        OS_PROJECT_NAME: admin
        OS_TENANT_NAME: admin
        OS_USERNAME: admin
        OS_USER_DOMAIN_NAME: "default"
        OS_PROJECT_DOMAIN_NAME: "default"
      retries: 10
      delay: 5
      register: endpoint_list

    - name: Creating Coriolis Keystone endpoints
      command: "openstack endpoint create migration {{ item.interface }} {{ item.url }}"
      environment:
        OS_AUTH_URL: "{{ keystone_auth_url }}"
        OS_IDENTITY_API_VERSION: 3
        OS_PASSWORD: "{{ keystone_admin_password }}"
        OS_PROJECT_NAME: admin
        OS_TENANT_NAME: admin
        OS_USERNAME: admin
        OS_USER_DOMAIN_NAME: "default"
        OS_PROJECT_DOMAIN_NAME: "default"
      run_once: True
      retries: 10
      delay: 5
      when: endpoint_list.stdout_lines == 0
      with_items:
        - {'interface': 'admin', 'url': '{{ coriolis_admin_endpoint }}'}
        - {'interface': 'internal', 'url': '{{ coriolis_internal_endpoint }}'}
        - {'interface': 'public', 'url': '{{ coriolis_public_endpoint }}'}

    - name: Checking Coriolis Keystone user
      shell: openstack user list  -c Name | grep {{ coriolis_keystone_user }}
      environment:
        OS_AUTH_URL: "{{ keystone_auth_url }}"
        OS_IDENTITY_API_VERSION: 3
        OS_PASSWORD: "{{ keystone_admin_password }}"
        OS_PROJECT_NAME: admin
        OS_TENANT_NAME: admin
        OS_USERNAME: admin
        OS_USER_DOMAIN_NAME: "default"
        OS_PROJECT_DOMAIN_NAME: "default"
      retries: 10
      delay: 5
      register: user_list

    - name: Creating Coriolis Keystone user
      command: "openstack user create --domain default --password {{ coriolis_keystone_password }} {{ coriolis_keystone_user }}"
      environment:
        OS_AUTH_URL: "{{ keystone_auth_url }}"
        OS_IDENTITY_API_VERSION: 3
        OS_PASSWORD: "{{ keystone_admin_password }}"
        OS_PROJECT_NAME: admin
        OS_TENANT_NAME: admin
        OS_USERNAME: admin
        OS_USER_DOMAIN_NAME: "default"
        OS_PROJECT_DOMAIN_NAME: "default"
      run_once: True
      retries: 10
      delay: 5
      when: user_list.stdout_lines == 0

    - name: Adding Coriolis Keystone user to the service admin role
      command: "openstack role add --project service --user {{ coriolis_keystone_user }} admin"
      environment:
        OS_AUTH_URL: "{{ keystone_auth_url }}"
        OS_IDENTITY_API_VERSION: 3
        OS_PASSWORD: "{{ keystone_admin_password }}"
        OS_PROJECT_NAME: admin
        OS_TENANT_NAME: admin
        OS_USERNAME: admin
        OS_USER_DOMAIN_NAME: "default"
        OS_PROJECT_DOMAIN_NAME: "default"
      run_once: True
      retries: 10
      delay: 5

    - name: coriolis-api container
      docker_container:
        name: coriolis-api
        image: coriolis-api:latest
        hostname: coriolis-api
        state: started
        restart_policy: unless-stopped
        network_mode: host
        volumes:
        - "/etc/coriolis:/etc/coriolis:ro"
        - "/var/log/coriolis:/var/log/coriolis:rw"
        ports:
        - "7667:7667"

    - name: coriolis-conductor container
      docker_container:
        name: coriolis-conductor
        image: coriolis-conductor:latest
        hostname: coriolis-conductor
        state: started
        restart_policy: unless-stopped
        network_mode: host
        volumes:
        - "/etc/coriolis:/etc/coriolis:ro"
        - "/var/log/coriolis:/var/log/coriolis:rw"

    - name: coriolis-worker container
      docker_container:
        name: coriolis-worker
        image: coriolis-worker:latest
        hostname: coriolis-worker
        state: started
        restart_policy: unless-stopped
        network_mode: host
        volumes:
        - "/etc/coriolis:/etc/coriolis:ro"
        - "/var/log/coriolis:/var/log/coriolis:rw"
        - "{{ coriolis_export_base_path_host }}:{{ coriolis_export_base_path }}:rw"
