---
- hosts: localhost
  vars:
      all_providers: "{{ export_providers | union(import_providers) }}"
  tasks:
    - name: Creating build directory
      file:
        path: ./build
        state: directory

    - name: Creating Proxy Docker build files
      template: src={{ docker_template }}/{{ item.name }}.j2 dest=./build/{{ item.name }}
      with_items:
        - { name: webproxy_start }
        - { name: Dockerfile.webproxy }

    - name: Building coriolis-web-proxy image
      docker_image:
        name: "{{ docker_registry }}/{{ coriolis_containers_namespace }}/coriolis-web-proxy"
        source: build
        build:
          dockerfile: Dockerfile.webproxy
          path: ./build
          pull: False
        push: "{{ docker_push_images }}"
        tag: "{{ docker_images_tag }}"
