FROM ubuntu:18.04

RUN apt-get update && apt-get install -y apache2 openssl
RUN a2enmod ssl headers rewrite proxy proxy_http proxy_wstunnel
RUN ln -s /etc/coriolis/coriolis-web-vhost.conf /etc/apache2/sites-enabled/coriolis-web-vhost.conf

# NOTE: the default site will take precedence over the Coriolis vhost(s) so
# HTTP connections on :80 will not automatically escalate to HTTPS on :443
RUN rm /etc/apache2/sites-enabled/000-default.conf || true

COPY ./webproxy_start /webproxy_start
RUN chmod 700 /webproxy_start

ENTRYPOINT ["/webproxy_start"]

EXPOSE 443
