FROM {{ docker_registry }}/{{ coriolis_containers_namespace }}/{{ docker_template }}/coriolis-common:{{ docker_images_tag }}
# Mapped volume: /etc/coriolis/coriolis.conf
ENTRYPOINT ["/bin/bash", "-c", "coriolis-replica-cron", "--config-file=/etc/coriolis/coriolis.conf"]
