FROM {{ docker_registry }}/{{ coriolis_containers_namespace }}/coriolis-common:{{ docker_images_tag }}

{% for item in all_providers %}
ADD coriolis-provider-{{item}}/ coriolis-provider-{{item}}
{% endfor %}

RUN add-apt-repository cloud-archive:rocky
RUN apt-get update && apt-get install -y librados2 python3-rados python3-rbd

RUN apt-get install -y vim
RUN apt-get install -y qemu-utils

# NOTE: the `openssl` binary is required by python-novaclient when
# decrypting the password of a Windows worker machine.
RUN apt-get install -y openssl

{% for item in all_providers %}
RUN /bin/bash -c "pip3 install -e ./coriolis-provider-{{item}}"
{% endfor %}

RUN apt-get install -y libnfs-dev libaio1
# NOTE: `libnfs` is required by `libqemu` but unused in the codepath(s)
# Coriolis will be calling so we can safely substitute for the new one:
RUN ln -s /usr/lib/x86_64-linux-gnu/libnfs.so.11.0.0 /usr/lib/x86_64-linux-gnu/libnfs.so.8
RUN ldconfig

ADD libqemu.so.gz /usr/lib/
RUN gunzip /usr/lib/libqemu.so.gz
RUN ldconfig

# Mapped volume: /etc/coriolis/coriolis.conf
ENTRYPOINT ["/bin/bash", "-c", "coriolis-worker", "--config-file={{ coriolis_config_directory_path }}/coriolis.conf"]
