FROM ubuntu:20.04

WORKDIR /root

# Required to prevent tzdata asking for a timezone:
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    python3-dev python3-cffi python3-pip \
    git wget curl vim

RUN /bin/bash -c "pip3 install python-openstackclient git+https://github.com/{{ custom_repo_owner_names['python-client'] | default('cloudbase') }}/python-coriolisclient@{{ custom_repo_branch_names['python-client'] | default('master') }}"
RUN echo "source /etc/kolla/admin-openrc.sh" >> /root/.bashrc

# NOTE: this will keep the container hanging indefinitely:
CMD ["tail", "-f", "/dev/null"]
