---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ coriolis_export_dir }}"
    - "{{ coriolis_vmware_vix_disklib_dir }}"
    - "{{ coriolis_hyperv_share_local_dir }}"
    - "{{ coriolis_vmware_vix_disklib_log_dir }}"

- name: Ensure libvirt provider DB file exists on the host
  file:
    path: "{{ coriolis_libvirt_provider_db_file }}"
    state: touch

# Some providers leverage the open-iscsi initiator (e.g. Nutanix).
# We must remove it from the host in order to avoid conflicts.
- name: Purge host open-iscsi
  shell: "apt-get -y purge open-iscsi"

- include_tasks: setup_worker_container.yml
