---
- name: Remove Docker container
  docker_container:
    state: absent
    name: coriolis-worker

- name: Remove Docker image
  docker_image:
    state: absent
    force_absent: yes
    name: "{{ docker_registry }}/{{ docker_namespace }}/coriolis-worker:{{ docker_images_tag }}"

- name: Remove directories
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - "{{ coriolis_export_dir }}"
    - "{{ coriolis_hyperv_share_local_dir }}"
    - "{{ coriolis_vmware_vix_disklib_dir }}"
    - "{{ vmware_vix_disklib_local_archive }}"
    - "{{ ceph_dir }}"
