---
- name: Setup coriolis-worker container
  docker_container:
    name: coriolis-worker
    image: "{{ coriolis_worker_docker_image_url }}"
    pull: "{{ docker_pull_images }}"
    hostname: "{{ coriolis_worker_service_hostname }}"
    state: started
    restart: yes
    restart_policy: unless-stopped
    network_mode: host
    volumes:
      - "{{ coriolis_config_dir }}:{{ coriolis_config_dir }}:ro"
      - "{{ coriolis_log_dir }}:{{ coriolis_log_dir }}"
      - "{{ coriolis_logger_socket_dir }}:{{ coriolis_logger_socket_dir }}"
      - "{{ coriolis_export_dir }}:{{ coriolis_export_dir }}:rw"
      - "{{ coriolis_vmware_vix_disklib_dir }}:{{ coriolis_vmware_vix_disklib_dir }}:ro"
      - "{{ appliance_coriolis_opt_tmp_dir }}:/tmp:rw"
      - "{{ coriolis_hyperv_share_local_dir }}:{{ coriolis_hyperv_share_local_dir }}:rw"
      - "{{ coriolis_profiling_dir_host }}/worker:{{ coriolis_profiling_dir_container }}"
