---
- name: Setup coriolis-worker container
  docker_container:
    name: coriolis-worker
    image: "{{ docker_registry }}/{{ docker_namespace }}/coriolis-worker:{{ docker_images_tag }}"
    pull: "{{ docker_pull_images }}"
    hostname: coriolis-worker
    state: started
    restart_policy: unless-stopped
    network_mode: host
    volumes:
      - "{{ coriolis_config_dir }}:{{ coriolis_config_dir }}:ro"
      - "{{ coriolis_log_dir }}:{{ coriolis_log_dir }}"
      - "{{ coriolis_logger_volume_name }}:{{ coriolis_logger_socket_dir }}"
      - "{{ ceph_dir }}:{{ ceph_dir }}:ro"
      - "{{ coriolis_export_dir }}:{{ coriolis_export_dir }}:rw"
      - "{{ coriolis_vmware_vix_disklib_dir }}:{{ coriolis_vmware_vix_disklib_dir }}:ro"
      - "{{ coriolis_hyperv_share_local_dir }}:{{ coriolis_hyperv_share_local_dir }}:rw"
