---
- name: Remove Docker container
  docker_container:
    state: absent
    name: coriolis-worker

- name: Remove Docker image
  docker_image:
    state: absent
    force_absent: yes
    name: "{{ docker_registry }}/{{ docker_namespace }}/coriolis-worker:{{ docker_images_tag }}"

- name: "Trigger coriolis-worker update"
  command: /bin/true
  notify:
    - "setup coriolis-worker"
