FROM {{ coriolis_common_docker_image_url }}

# Mapped volume: /etc/coriolis/coriolis.conf

{% if "minion-manager" in enable_profiling_for %}
CMD ["/usr/local/bin/fil-profile", "-o", "{{ coriolis_profiling_dir_container }}", "run", "/usr/local/bin/coriolis-minion-manager", "--config-file={{ coriolis_config_dir }}/coriolis.conf", "--config-file={{ coriolis_config_dir }}/coriolis-minion-manager-logging.conf"]
{% else %}
CMD ["/bin/bash", "-c", "coriolis-minion-manager", "--config-file={{ coriolis_config_dir }}/coriolis.conf"]
{% endif %}
