FROM {{ docker_registry }}/coriolis-base:{{ docker_images_tag }}

WORKDIR /root

ADD coriolis-core/ coriolis-core
RUN /bin/bash -c "pip3 install ./coriolis-core"

# This can be mapped in a volume
RUN mkdir -p /var/log/coriolis
