FROM {{ docker_registry }}/coriolis-common:{{ docker_images_tag }}

ADD coriolis-provider-oracle-vm/ coriolis-provider-oracle-vm
ADD coriolis-provider-opc/ coriolis-provider-opc
ADD coriolis-provider-vmware/ coriolis-provider-vmware
ADD coriolis-provider-openstack/ coriolis-provider-openstack

RUN yum install -y qemu-img
# NOTE: the `openssl` binary is required by python-novaclient when
# decrypting the password of a Windows worker machine.
RUN yum install -y openssl

RUN /bin/bash -c "pip3 install ./coriolis-provider-oracle-vm"
RUN /bin/bash -c "pip3 install ./coriolis-provider-opc"
RUN /bin/bash -c "pip3 install ./coriolis-provider-vmware"
RUN /bin/bash -c "pip3 install ./coriolis-provider-openstack"

ADD libnfs.x86_64.rpm /root
RUN rpm -Uvh libnfs.x86_64.rpm

RUN mkdir -p /usr/lib/libqemu
ADD libqemu.so.gz /usr/lib/
RUN gunzip /usr/lib/libqemu.so.gz
RUN ldconfig

ADD VMware-vix-disklib.tar.gz /root
RUN mkdir -p /usr/lib/vmware
RUN mv vmware-vix-disklib-distrib/lib64/* /usr/lib/vmware/
RUN mv vmware-vix-disklib-distrib/bin64/* /usr/local/bin/
RUN ln -s /usr/lib/vmware/libvixDiskLib.so /usr/lib/libvixDiskLib.so
RUN ldconfig

# Mapped volume: /etc/coriolis/coriolis.conf
ENTRYPOINT ["/bin/bash", "-c", "coriolis-worker", "--config-file=/etc/coriolis/coriolis.conf"]
