FROM {{ docker_registry }}/coriolis-common:{{ docker_images_tag }}
# Mapped volume: /etc/coriolis/coriolis.conf
ENTRYPOINT ["/bin/bash", "-c", "coriolis-api", "--config-file=/etc/coriolis/coriolis.conf"]
EXPOSE 7667
