FROM oraclelinux:7

WORKDIR /root

RUN curl --silent --location https://rpm.nodesource.com/setup_9.x | bash -
RUN yum install -y nodejs
RUN curl -o /etc/yum.repos.d/yarn.repo https://dl.yarnpkg.com/rpm/yarn.repo
RUN yum install -y yarn

ADD coriolis-web/ coriolis-web
WORKDIR coriolis-web
RUN yarn install --production --no-progress
RUN yarn build

ENTRYPOINT [ "node", "server.js" ]

EXPOSE 3000
