FROM oraclelinux:7

RUN yum install -y httpd openssl mod_ssl
COPY ./coriolis-web-vhost.conf /etc/httpd/conf.d/coriolis-web-vhost.conf

COPY ./webproxy_start /webproxy_start
RUN chmod 700 /webproxy_start

ENTRYPOINT ["/webproxy_start"]

EXPOSE 443
