FROM coriolis-common:latest
# Mapped volume: /etc/coriolis/coriolis.conf
CMD /bin/bash -c python3 coriolis-core/coriolis/cmd/db_sync.py; /bin/bash -c coriolis-conductor --config-file=/etc/coriolis/coriolis.conf
