FROM {{ docker_images_namespace }}/coriolis-common:{{ docker_images_tag }}

# Mapped volume: /etc/coriolis/coriolis.conf
CMD ["/bin/bash", "-c", "coriolis-replica-cron", "--config-file={{ coriolis_config_dir }}/coriolis.conf"]
