FROM golang:1.13 AS builder
LABEL stage=builder

COPY coriolis-licensing-server/ /tmp/coriolis-licensing-server

WORKDIR /tmp/coriolis-licensing-server/server
ENV GO111MODULE=on
RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -a -ldflags="-w -s" -o /server .

FROM busybox
COPY --from=builder /server /server

# NOTE: the afferent port is exposed in the Ansible playbook.
ENTRYPOINT ["/bin/sh", "-c", "/server start --port $LICENSING_SERVER_PORT --database $LICENSING_DB_STRING --hostname $LICENSING_HOSTNAME"]
