FROM golang:1.13

COPY coriolis-licensing-server/ /tmp/coriolis-licensing-server

WORKDIR /tmp/coriolis-licensing-server/server
ENV GO111MODULE=on
RUN go build -o "$GOPATH/bin/server" .

WORKDIR /
RUN rm -rf /tmp/coriolis-licensing-server

# NOTE: the afferent port is exposed in the Ansible playbook.
ENTRYPOINT ["/bin/bash", "-c", "$GOPATH/bin/server start --port $LICENSING_SERVER_PORT --database $LICENSING_DB_STRING --hostname $LICENSING_HOSTNAME"]
