[DEFAULT]
messaging_transport_url=rabbit://coriolis:Passw0rd@coriolis-rabbitmq:5672/
log_dir=/var/log/coriolis
#log_file=coriolis.log
debug=true
providers=coriolis_provider_openstack.ExportProvider,coriolis_provider_openstack.ImportProvider,coriolis_provider_vmware_vsphere.ExportProvider,coriolis_provider_oracle_vm.ImportProvider

[database]
connection = mysql://coriolis:Passw0rd@172.16.201.149/coriolis

[keystone_authtoken]
auth_type = password
#auth_url = http://10.197.239.3:35357
auth_url = http://10.89.13.195:35357/v3
username = coriolis
user_domain_id = default
password = Passw0rd
#password = 9c86a7cef1544c61
project_name = service
#project_name = services
project_domain_id = default

[trustee]
auth_type = password
auth_url = http://10.89.13.195:35357/v3
username = coriolis
user_domain_id = default
password = Passw0rd
#project_name = service
#project_domain_id = default

#auth_uri=http://10.197.239.3:5000/v2.0
#identity_uri=http://10.197.239.3:35357
#admin_user=nova
#admin_password=9c86a7cef1544c61
#admin_tenant_name=services

[keystone]
auth_url = http://10.89.13.195:5000/v2.0
#auth_url = http://10.197.239.3:5000/v2.0

[openstack_migration_provider]
#disk_format = vhd
#hypervisor_type = hyperv
#migr_image_name_map = linux: Ubuntu 15.10, windows: Windows Server 2012 R2 Std Eval
migr_image_name_map = linux: Ubuntu 15.10, windows: Nano

migr_flavor_name = coriolis-demo-migr

[oracle_vm_migration_provider]
migr_template_name_map = linux: OracleLinux7_template, windows: WS2016_template
migr_template_username = root
migr_template_password = Passw0rd
migr_network_name = Management
server_pool_name = pool1
repository_name = repo1

[oracle_vm_windows_images]
pv_drivers_url = https://dl.dropboxusercontent.com/u/9060190/ovm_win_vp_drivers_3_2_3.zip

[serialization]

temp_keypair_password = blahblah

