FROM {{ docker_registry }}/{{ docker_namespace }}/coriolis-common:{{ docker_images_tag }}

# Mapped volume: /etc/coriolis/coriolis.conf
CMD ["/usr/local/bin/coriolis-conductor", "--config-file={{ coriolis_config_dir }}/coriolis.conf", "--config-file={{ coriolis_config_dir }}/coriolis-conductor-logging.conf"]
