FROM {{ coriolis_common_docker_image_url }}

# Mapped volume: /etc/coriolis/coriolis.conf

{% if "deployer_manager" in enable_profiling_for %}
CMD ["/usr/local/fil-profile", "-o", "{{ coriolis_profiling_dir_container }}", "run", "/usr/local/bin/coriolis-deployer-manager", "--config-file={{ coriolis_config_dir }}/coriolis-conf", "--config-file={{ coriolis_config_dir }}/coriolis-deployer-manager-logging.conf"]
{% else %}
CMD ["/bin/bash", "-c", "coriolis-deployer-manager", "--config-file={{ coriolis_config_dir }}/coriolis-conf", "--config-file={{ coriolis_config_dir }}/coriolis-deployer-manager-logging.conf"]
{% endif %}
