FROM ubuntu:20.04

WORKDIR /root

# Required to prevent tzdata asking for a timezone:
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    python3-dev python3-cffi python3-pip \
    gcc make git zlib1g-dev libmysqlclient-dev \
    software-properties-common build-essential libssl-dev pkg-config

RUN /bin/bash -c "pip3 install -U pip"
RUN /bin/bash -c "pip3 install wheel"

{% if enable_profiling_for %}
RUN /bin/bash -c "pip3 install filprofiler"
{% endif %}

COPY coriolis-common-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

COPY coriolis-core coriolis-core

RUN /bin/bash -c "pip3 install git+https://github.com/cloudbase/pywinrm.git@requests#egg=pywinrm"
RUN /bin/bash -c "pip3 install -e ./coriolis-core"

COPY coriolis-replicator/replicator coriolis-core/coriolis/resources/bin/replicator
COPY coriolis-writer/writer         coriolis-core/coriolis/resources/bin/coriolis-writer

# This can be mapped in a volume
RUN mkdir -p /var/log/coriolis

ENTRYPOINT ["/entrypoint.sh"]
