---
- name: "build coriolis-conductor"
  listen: "build coriolis core components"
  include_tasks: "{{ playbook_dir }}/roles/common/docker/tasks/build_image.yml"
  vars:
    image_name: coriolis-conductor
    image_tag: "{{ coriolis_conductor_docker_image_tag }}"

- name: "restart coriolis-conductor"
  listen: "restart coriolis core components"
  shell: "docker restart coriolis-conductor"
