---
- name: Setup step-ca container
  docker_container:
    name: step-ca
    image: "{{ step_ca_image }}"
    pull: "{{ docker_pull_images }}"
    hostname: step-ca
    state: started
    restart_policy: unless-stopped
    network_mode: bridge
    ports:
      - "{{ step_ca_port }}:{{ step_ca_port }}"
    env:
      DOCKER_STEPCA_INIT_NAME: "MetalHubCA"
      DOCKER_STEPCA_INIT_DNS_NAMES: "localhost,coriolis,{{ bind_address }}"
    volumes:
      - "{{ step_ca_home }}:/home/step:rw"
