---
custom_repo_owner_names: {}
custom_repo_branch_names: {}

libqemu_url: https://cloudbase.it/downloads/libqemu.so.gz
vmware_vix_disklib_url: http://cloudbase.it/downloads/VMware-vix-disklib-6.7.3-18758564.x86_64.tar.gz
vmware_vix_disklib_local_archive: "/tmp/VMware-vix-disklib.tar.gz"
ovirt_sdk_wheel_url: https://cloudbase.it/downloads/ovirt_engine_sdk_python-4.4.15-cp38-cp38-linux_x86_64.whl
coriolis_worker_docker_image_url: "{{ docker_registry }}/{{ docker_namespace }}/coriolis-worker:{{ coriolis_worker_docker_image_tag }}"
