---
custom_repo_owner_names: {}
custom_repo_branch_names: {}

libqemu_url: https://cloudbase.it/downloads/libqemu.so.gz
coriolis_worker_docker_image_url: "{{ docker_registry }}/{{ docker_namespace }}/coriolis-worker:{{ coriolis_worker_docker_image_tag }}"
