---
- name: coriolis-compressor container
  docker_container:
    name: coriolis-compressor
    image: "{{ coriolis_compressor_docker_image_url }}"
    pull: "{{ docker_pull_images }}"
    hostname: coriolis-compressor
    state: started
    restart: yes
    restart_policy: unless-stopped
    network_mode: host
    env:
      COMPRESSOR_ADDRESS: "{{ compressor_address }}"
