---
- name: coriolis-compressor container
  docker_container:
    name: coriolis-compressor
    image: "{{ docker_registry }}/{{ docker_namespace }}/coriolis-compressor:{{ docker_images_tag }}"
    pull: "{{ docker_pull_images }}"
    hostname: coriolis-compressor
    state: started
    restart: yes
    restart_policy: unless-stopped
    network_mode: host
    env:
      COMPRESSOR_ADDRESS: "{{ compressor_address }}"
