---
- name: Get resources directory stat
  stat:
    path: "{{ coriolis_resources_bin_dir }}"
  register: resources_dir_info

- name: Set Docker volumes list
  block:
    - set_fact:
        docker_volumes_list:
          - "{{ coriolis_config_dir }}:{{ coriolis_config_dir }}:ro"
          - "{{ coriolis_log_dir }}:{{ coriolis_log_dir }}"
          - "{{ coriolis_logger_volume_name }}:{{ coriolis_logger_socket_dir }}"

    - set_fact:
        docker_volumes_list: "{{ docker_volumes_list + [(coriolis_resources_bin_dir + ':' + coriolis_container_resources_bin_dir)] }}"
      when: resources_dir_info.stat.exists

- name: Setup coriolis-conductor container
  docker_container:
    name: coriolis-conductor
    image: "{{ docker_images_namespace }}/coriolis-conductor:{{ docker_images_tag }}"
    pull: "{{ docker_pull_images }}"
    hostname: coriolis-conductor
    state: started
    restart_policy: unless-stopped
    network_mode: host
    env:
      LICENSING_SERVER_BASE_URL: "{{ coriolis_licensing_server_endpoint if enable_coriolis_licensing_server else '' }}"
      LICENSING_SERVER_ALLOW_UNTRUSTED: "true"
      RUN_DBSYNC: "yes"
    volumes: "{{ docker_volumes_list }}"
