---
- name: Remove Docker container
  docker_container:
    state: absent
    name: coriolis-conductor

- name: Remove Docker image
  docker_image:
    state: absent
    force_absent: yes
    name: "{{ docker_registry }}/{{ docker_namespace }}/coriolis-conductor:{{ docker_images_tag }}"

- include_tasks: setup_conductor_container.yml
