---
- name: Create build directory
  file:
    path: "{{ build_dir }}"
    state: directory

- name: Clone git repository
  git:
    repo: "git@bitbucket.org:{{ repo_owner }}/coriolis-licensing-server.git"
    dest: "{{ build_dir }}/coriolis-licensing-server"
    update: yes
    force: yes
    version: "{{ repo_branch }}"
    key_file: "{{ bitbucket_ssh_key_file if bitbucket_ssh_key_file is defined else '' }}"
    accept_hostkey: yes
  vars:
    repo_owner: "{{ custom_repo_owner_names['licensing-server'] | default('cloudbase') }}"
    repo_branch: "{{ custom_repo_branch_names['licensing-server'] | default('master') }}"
  register: result
  retries: 10
  delay: 5
  until: result is succeeded
  notify:
    - "build coriolis-licensing-server"

- name: Render template
  template:
    src: Dockerfile.j2
    dest: "{{ build_dir }}/coriolis-licensing-server.Dockerfile"
  notify:
    - "build coriolis-licensing-server"

- import_role:
    name: common/docker
    tasks_from: build_image
  vars:
    image_name: coriolis-licensing-server
    remove_existing: false
