FROM golang:1.13 AS builder
LABEL stage=builder

ENV GO111MODULE=on
COPY coriolis-logger/ /tmp/coriolis-logger
WORKDIR /tmp/coriolis-logger/cmd/coriolis-logger/

RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -a -ldflags="-w -s" -o /coriolis-logger .

FROM busybox
COPY --from=builder /coriolis-logger /coriolis-logger
RUN chmod +x /coriolis-logger

ENTRYPOINT ["/coriolis-logger", "-config", "{{ coriolis_logger_config_dir }}/coriolis-logger.toml"]
