---
- name: Create build directory
  file:
    path: "{{ build_dir }}"
    state: directory

- name: Clone coriolis-replicator
  git:
    repo: "git@bitbucket.org:{{ repo_owner }}/coriolis-replicator"
    dest: "{{ build_dir }}/coriolis-replicator"
    update: yes
    force: yes
    version: "{{ repo_branch }}"
    key_file: "{{ bitbucket_ssh_key_file if bitbucket_ssh_key_file is defined else '' }}"
    accept_hostkey: yes
  vars:
    repo_owner: "{{ custom_repo_owner_names['replicator'] | default('cloudbase') }}"
    repo_branch: "{{ custom_repo_branch_names['replicator'] | default('master') }}"
  register: result
  retries: 10
  delay: 5
  until: result is succeeded
  notify:
    - "build coriolis core components"

- name: Clone coriolis-writer
  git:
    repo: "git@bitbucket.org:{{ repo_owner }}/coriolis-writer"
    dest: "{{ build_dir }}/coriolis-writer"
    update: yes
    force: yes
    version: "{{ repo_branch }}"
    key_file: "{{ bitbucket_ssh_key_file if bitbucket_ssh_key_file is defined else '' }}"
    accept_hostkey: yes
  vars:
    repo_owner: "{{ custom_repo_owner_names['writer'] | default('cloudbase') }}"
    repo_branch: "{{ custom_repo_branch_names['writer'] | default('master') }}"
  register: result
  retries: 10
  delay: 5
  until: result is succeeded
  notify:
    - "build coriolis core components"

- name: Clone coriolis core
  git:
    repo: "https://github.com/{{ repo_owner }}/coriolis"
    dest: "{{ build_dir }}/coriolis-core"
    update: yes
    force: yes
    version: "{{ repo_branch }}"
  vars:
    repo_owner: "{{ custom_repo_owner_names['core'] | default('cloudbase') }}"
    repo_branch: "{{ custom_repo_branch_names['core'] | default('master') }}"
  register: result
  retries: 10
  delay: 5
  until: result is succeeded
  notify:
    - "build coriolis core components"

- name: Render templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "Dockerfile.j2",    dest: "{{ build_dir }}/coriolis-common.Dockerfile" }
    - { src: "entrypoint.sh.j2", dest: "{{ build_dir }}/coriolis-common-entrypoint.sh" }
  notify:
    - "build coriolis core components"

- name: "Get Docker image stat"
  docker_image_info:
    name: "{{ docker_registry }}/{{ docker_namespace }}/coriolis-common:{{ docker_images_tag }}"
  register: docker_image_info

- name: Get coriolis-replicator file stat
  stat:
    path: "{{ build_dir }}/coriolis-replicator/cmd/replicator"
  register: coriolis_replicator_file

- name: Get coriolis-writer file stat
  stat:
    path: "{{ build_dir }}/coriolis-writer/cmd/writer"
  register: coriolis_writer_file

- name: "Trigger core components build"
  command: /bin/true
  notify:
    - "build coriolis core components"
  when: ((not coriolis_replicator_file.stat.exists) or
         (not coriolis_writer_file.stat.exists) or
         (docker_image_info.images | length == 0))
