---
- name: Get resources directory stat
  stat:
    path: "{{ coriolis_resources_bin_dir }}"
  register: resources_dir_info

- name: Set Docker volumes list
  block:
    - set_fact:
        docker_volumes_list:
          - "{{ coriolis_config_dir }}:{{ coriolis_config_dir }}:ro"
          - "{{ coriolis_log_dir }}:{{ coriolis_log_dir }}"
          - "{{ coriolis_logger_volume_name }}:{{ coriolis_logger_socket_dir }}"

    - set_fact:
        docker_volumes_list: "{{ docker_volumes_list + [(coriolis_resources_bin_dir + ':' + coriolis_container_resources_bin_dir)] }}"
      when: resources_dir_info.stat.exists

- name: Setup coriolis-replica-cron container
  docker_container:
    name: coriolis-replica-cron
    image: "{{ docker_registry }}/{{ docker_namespace }}/coriolis-replica-cron:{{ docker_images_tag }}"
    pull: "{{ docker_pull_images }}"
    hostname: coriolis-replica-cron
    state: started
    restart: "{{ restart }}"
    restart_policy: unless-stopped
    network_mode: host
    volumes: "{{ docker_volumes_list }}"
