---
- name: Remove Docker container
  docker_container:
    state: absent
    name: coriolis-replica-cron

- name: Remove Docker image
  docker_image:
    state: absent
    force_absent: yes
    name: "{{ docker_registry }}/{{ docker_namespace }}/coriolis-replica-cron"

- name: "Trigger coriolis-replica-cron update"
  command: /bin/true
  notify:
    - "setup coriolis-replica-cron"
