---
- name: Remove Docker container
  docker_container:
    state: absent
    name: coriolis-replica-cron

- name: Remove Docker image
  docker_image:
    state: absent
    force_absent: yes
    name: "{{ docker_images_namespace }}/coriolis-replica-cron:{{ docker_images_tag }}"

- include_tasks: setup_replica_cron_container.yml
