FROM {{ coriolis_common_docker_image_url }}

# Mapped volume: /etc/coriolis/coriolis.conf
{% if "transfer-cron" in enable_profiling_for %}
CMD ["/usr/local/bin/fil-profile", "-o", "{{ coriolis_profiling_dir_container }}", "run", "/usr/local/bin/coriolis-transfer-cron", "--config-file={{ coriolis_config_dir }}/coriolis.conf", "--config-file={{ coriolis_config_dir }}/coriolis-transfer-cron-logging.conf"]
{% else %}
CMD ["/usr/local/bin/coriolis-transfer-cron", "--config-file={{ coriolis_config_dir }}/coriolis.conf", "--config-file={{ coriolis_config_dir }}/coriolis-transfer-cron-logging.conf"]
{% endif %}
