FROM {{ docker_registry }}/{{ coriolis_containers_namespace }}/coriolis-common:{{ docker_images_tag }}

# Mapped volume: /etc/coriolis/coriolis.conf
ENTRYPOINT ["/bin/bash", "-c", "coriolis-api", "--config-file=/etc/coriolis/coriolis.conf"]
EXPOSE 7667
