FROM golang:1.13

ENV GO111MODULE=on
ADD coriolis-logger/ /tmp/coriolis-logger
WORKDIR /tmp/coriolis-logger/cmd/coriolis-logger/

RUN go build -o /usr/local/bin/coriolis-logger .

WORKDIR /
RUN rm -rf "/tmp/coriolis-logger"
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/usr/local/bin/coriolis-logger", "-config", "{{coriolis_logger_config}}"]
