FROM ubuntu:16.04

WORKDIR /root

RUN apt-get update && apt-get install -y \
    python3-dev python3-cffi python3-pip \
    gcc make git python3-pip zlib1g-dev libmysqlclient-dev \
    software-properties-common

RUN /bin/bash -c "pip3 install -U pip"
RUN /bin/bash -c "pip3 install wheel"
