---
- name: "build coriolis replicator"
  listen: "build coriolis core components"
  include_tasks: "{{ role_path }}/tasks/build_replicator.yml"

- name: "build coriolis writer"
  listen: "build coriolis core components"
  include_tasks: "{{ role_path }}/tasks/build_writer.yml"

- name: "build coriolis-common"
  listen: "build coriolis core components"
  include_tasks: "{{ playbook_dir }}/roles/common/docker/tasks/build_image.yml"
  vars:
    image_name: coriolis-common
    image_tag: "{{ coriolis_common_docker_image_tag }}"

- name: Reload sshd
  ansible.builtin.systemd_service:
    name: ssh
    state: reloaded
