FROM {{ docker_registry }}/{{ docker_namespace }}/coriolis-common:{{ docker_images_tag }}

# Mapped volume: /etc/coriolis/coriolis.conf
CMD ["/usr/local/bin/coriolis-api", "--config-file={{ coriolis_config_dir }}/coriolis.conf"]
EXPOSE 7667
