---
- name: "build coriolis-web-proxy"
  include_tasks: "{{ playbook_dir }}/roles/common/docker/tasks/build_image.yml"
  vars:
    image_name: coriolis-web-proxy
    remove_existing: true

- name: "setup coriolis-web-proxy"
  include_tasks: "{{ role_path }}/tasks/setup_web_proxy_container.yml"
  vars:
    restart: yes
