FROM {{ coriolis_common_docker_image_url }}

RUN pip install -e /root/coriolis-core

{% for item in coriolis_providers %}
COPY coriolis-provider-{{ item }}/ coriolis-provider-{{ item }}
{% endfor %}

RUN add-apt-repository -y cloud-archive:antelope
RUN apt-get update && apt-get install -y librados2 python3-rados python3-rbd

RUN apt-get install -y vim
RUN apt-get install -y qemu-utils

{% if "metal" in coriolis_providers %}
COPY python-coriolismetalhubclient/ python-coriolismetalhubclient
RUN /bin/bash -c "pip3 install ./python-coriolismetalhubclient"
{% endif %}

{% if "openstack" in coriolis_providers %}
# NOTE: the `openssl` binary is required by python-novaclient when
# decrypting the password of a Windows worker machine retrieved
# using `nova get-password`
RUN apt-get install -y openssl
{% endif %}

{% if "ovirt" in coriolis_providers %}
# NOTE: ovirt depends on `pycurl`, which requires the below as well as `libssl-dev`
# (installed in the `coriolis-common` image) to be `pip3 install`d.
RUN apt-get install -y libcurl4-openssl-dev libxml2-dev
{% endif %}

{% if "libvirt" in coriolis_providers %}
#NOTE: libvirt provider generates config drive, so it needs the following packages installed:
RUN apt-get install -y libvirt-dev genisoimage
{% endif %}

{% if "nutanix" in coriolis_providers %}
#NOTE: the Nutanix provider uses iSCSI to retrieve disk data. We'll install
# the open-iscsi package and use an entry point script to launch the service.
RUN apt-get install -y open-iscsi
ENV RUN_OPENISCSI yes
{% endif %}

{% for item in coriolis_providers %}
RUN /bin/bash -c "pip3 install -e ./coriolis-provider-{{ item }}"
{% endfor %}

# NOTE: `libnfs` is required by `libqemu` but unused in the codepath(s)
# Coriolis will be calling so we can safely substitute for the new one:
RUN apt-get install -y libnfs-dev libaio1
RUN ln -s /usr/lib/x86_64-linux-gnu/libnfs.so.11.0.0 /usr/lib/x86_64-linux-gnu/libnfs.so.8
RUN ldconfig

COPY libqemu.so.gz /usr/lib/
RUN gunzip /usr/lib/libqemu.so.gz
RUN ldconfig

# Mapped volume: /etc/coriolis/coriolis.conf
{% if "worker" in enable_profiling_for %}
CMD ["/usr/local/bin/fil-profile", "-o", "{{ coriolis_profiling_dir_container}}", "run", "/usr/local/bin/coriolis-worker", "--config-file={{coriolis_config_dir }}/coriolis.conf", "--config-file={{ coriolis_config_dir}}/coriolis-worker-logging.conf", "--worker-process-count", "1"]
{% else %}
CMD ["/usr/local/bin/coriolis-worker", "--config-file={{ coriolis_config_dir }}/coriolis.conf"]
{% endif %}
