FROM {{ docker_registry }}/{{ docker_namespace }}/coriolis-common:{{ docker_images_tag }}

{% for item in coriolis_providers %}
COPY coriolis-provider-{{ item }}/ coriolis-provider-{{ item }}
{% endfor %}

RUN add-apt-repository cloud-archive:train
RUN apt-get update && apt-get install -y librados2 python3-rados python3-rbd

RUN apt-get install -y vim
RUN apt-get install -y qemu-utils

# NOTE: the `openssl` binary is required by python-novaclient when
# decrypting the password of a Windows worker machine.
RUN apt-get install -y openssl

{% for item in coriolis_providers %}
RUN /bin/bash -c "pip3 install -e ./coriolis-provider-{{ item }}"
{% endfor %}

# NOTE: `libnfs` is required by `libqemu` but unused in the codepath(s)
# Coriolis will be calling so we can safely substitute for the new one:
RUN apt-get install -y libnfs-dev libaio1
RUN ln -s /usr/lib/x86_64-linux-gnu/libnfs.so.11.0.0 /usr/lib/x86_64-linux-gnu/libnfs.so.8
RUN ldconfig

COPY libqemu.so.gz /usr/lib/
RUN gunzip /usr/lib/libqemu.so.gz
RUN ldconfig

# Mapped volume: /etc/coriolis/coriolis.conf
CMD ["/bin/bash", "-c", "coriolis-worker", "--config-file={{ coriolis_config_dir }}/coriolis.conf", "--config-file={{ coriolis_config_dir }}/coriolis-worker-logging.conf"]
