FROM {{ coriolis_licensing_ui_base_image }}

RUN curl -o- -L https://yarnpkg.com/install.sh | bash

ENV BASENAME=/licensing-ui

WORKDIR /usr/src/app
ADD coriolis-licensing-ui ./

RUN yarn install
RUN yarn build

ENTRYPOINT [ "node", "server.js" ]
# NOTE: the afferent port is exposed in the Ansible playbook.
