---
- name: Setup coriolis-minion-manager container
  docker_container:
    name: coriolis-minion-manager
    image: "{{ coriolis_minion_manager_docker_image_url }}"
    pull: "{{ docker_pull_images }}"
    hostname: coriolis-minion-manager
    state: started
    restart_policy: unless-stopped
    network_mode: host
    volumes:
      - "{{ coriolis_config_dir }}:{{ coriolis_config_dir }}:ro"
      - "{{ coriolis_log_dir }}:{{ coriolis_log_dir }}"
      - "{{ coriolis_logger_volume_name }}:{{ coriolis_logger_socket_dir }}"
      - "{{ coriolis_minion_manager_locks_dir_host }}:{{ coriolis_locks_dir_containers }}"
      - "{{ coriolis_profiling_dir_host }}/minion-manager:{{ coriolis_profiling_dir_container }}"
